#!/usr/bin/env python3
"""Generate Bootstrap Icon font modules and icon lookup map for Pico Admin.

Run from the project root.

Usage:
    # Preferred — reads sizes and icon lists from tools/icons-config.json:
    ./tools/build-icons.sh

    # Or call directly:
    python tools/lib/gen_icons.py

    # Explicit override (bypass icons-config.json):
    python tools/lib/gen_icons.py --icons alarm wifi battery-full --sizes 24 36

    # Generate for ALL ~2000 icons (large files, use only if you need them all):
    python tools/lib/gen_icons.py --all --sizes 24

Outputs written to firmware/assets/icons/:
    icons_map.py               — compact Python dict: name -> unicode char
                                 (union of all icons across all configured sizes)
    bootstrap_icons_{size}.py  — font_to_py module per size (per-size icon subset)

Prerequisites:
    pip install micropython-font-to-py

Source assets (not uploaded to Pico):
    assets/icons/bootstrap-icons.ttf
    assets/icons/bootstrap-icons-map.json
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ICONS_TTF = ROOT / "assets" / "icons" / "bootstrap-icons.ttf"
ICONS_MAP_JSON = ROOT / "assets" / "icons" / "bootstrap-icons-map.json"
ICONS_JSON = ROOT / "tools" / "icons-config.json"
OUT_DIR = ROOT / "firmware" / "assets" / "icons"


def load_full_map() -> dict:
    with open(ICONS_MAP_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def load_icons_json(path: Path) -> dict:
    """Load tools/icons-config.json → {size_int: [name, ...]}. Skips keys starting with '_'."""
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    result = {}
    for k, v in raw.items():
        if k.startswith("_"):
            continue
        try:
            size = int(k)
        except ValueError:
            print(
                f"WARNING: icons-config.json key {k!r} is not an integer size, skipping."
            )
            continue
        result[size] = v
    return result


def resolve_names(names: list, full_map: dict) -> tuple:
    """Resolve icon names against the full Bootstrap map. Returns (selected_dict, missing_list)."""
    selected = {}
    missing = []
    for name in names:
        if name in full_map:
            selected[name] = full_map[name]
        else:
            missing.append(name)
    return selected, missing


def generate_icons_map(selected: dict, out_dir: Path) -> None:
    """Write the union-of-all-sizes icon lookup dict to icons_map.py."""
    out_path = out_dir / "icons_map.py"
    lines = [
        "# Auto-generated by tools/lib/gen_icons.py — do not edit by hand.",
        "# Re-run: ./tools/build-icons.sh",
        "",
        "ICONS = {",
    ]
    for name, char in sorted(selected.items()):
        cp = ord(char)
        lines.append(f'    "{name}": "\\u{cp:04x}",  # {name}')
    lines += [
        "}",
        "",
        "",
        'def get(name: str, fallback: str = "?") -> str:',
        '    """Return the unicode glyph char for icon name, or fallback."""',
        "    return ICONS.get(name, fallback)",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Written: {out_path.relative_to(ROOT)}")


def generate_font_module(chars: str, size: int, out_dir: Path) -> None:
    """Run font_to_py to produce bootstrap_icons_{size}.py."""
    out_filename = f"bootstrap_icons_{size}.py"
    out_path = out_dir / out_filename

    # font_to_py validates that the output stem is a valid Python identifier.
    # Some versions check the raw string before extracting basename, so a full
    # path fails the check. Run with cwd=out_dir and pass just the filename.
    base_cmd = [
        "-x",  # include extended (non-ASCII) characters
        "-c",
        chars,
        str(ICONS_TTF),
        str(size),
        out_filename,
    ]

    # Try `python -m font_to_py` first, fall back to `font_to_py` script on PATH.
    for cmd in [
        [sys.executable, "-m", "font_to_py"] + base_cmd,
        ["font_to_py"] + base_cmd,
    ]:
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=out_dir)
        if result.returncode == 0:
            print(f"  Written: {out_path.relative_to(ROOT)}")
            return

    print(f"  ERROR running font_to_py for size {size}:")
    print(result.stderr or result.stdout)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument(
        "--icons",
        nargs="+",
        metavar="NAME",
        help="Icon names to include (overrides icons-config.json; requires --sizes)",
    )
    group.add_argument(
        "--all", action="store_true", help="Include all ~2000 Bootstrap icons"
    )
    parser.add_argument(
        "--sizes",
        nargs="+",
        type=int,
        metavar="PX",
        help="Font sizes in pixels — used with --icons / --all; ignored when reading icons-config.json",
    )
    args = parser.parse_args()

    if not ICONS_TTF.exists():
        sys.exit(f"ERROR: TTF not found at {ICONS_TTF}")
    if not ICONS_MAP_JSON.exists():
        sys.exit(f"ERROR: Map not found at {ICONS_MAP_JSON}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    full_map = load_full_map()

    # ── explicit overrides (--icons / --all) ───────────────────────────────────────────
    if args.all or args.icons:
        sizes = args.sizes or [24]
        if args.all:
            icon_set = full_map
        else:
            icon_set, missing = resolve_names(args.icons, full_map)
            if missing:
                print(f"WARNING: unknown icon names (skipped): {', '.join(missing)}")
            if not icon_set:
                sys.exit("ERROR: no valid icon names found.")

        print(
            f"\nGenerating {len(icon_set)} icon(s) at size(s) {sizes} (explicit)...\n"
        )
        generate_icons_map(icon_set, OUT_DIR)
        chars = "".join(icon_set.values())
        for size in sizes:
            generate_font_module(chars, size, OUT_DIR)

    # ── default: read tools/icons-config.json ─────────────────────────────────────────────────
    else:
        if not ICONS_JSON.exists():
            sys.exit(
                f"ERROR: {ICONS_JSON} not found. Create it or use --icons / --all."
            )

        size_map = load_icons_json(ICONS_JSON)
        if not size_map:
            sys.exit(f"ERROR: {ICONS_JSON} contains no size entries.")

        sizes_str = ", ".join(str(s) for s in sorted(size_map))
        print(
            f"Reading {ICONS_JSON.relative_to(ROOT)} — {len(size_map)} size(s): {sizes_str}\n"
        )

        union_icons = {}  # accumulate across all sizes for icons_map.py

        for size in sorted(size_map):
            names = size_map[size]
            selected, missing = resolve_names(names, full_map)
            if missing:
                print(
                    f"  [{size}px] WARNING: unknown icons (skipped): {', '.join(missing)}"
                )
            if not selected:
                print(f"  [{size}px] WARNING: no valid icons — skipping.")
                continue
            union_icons.update(selected)
            print(f"  [{size}px] {len(selected)} icon(s)")
            generate_font_module("".join(selected.values()), size, OUT_DIR)

        if not union_icons:
            sys.exit("ERROR: no valid icon names found in icons-config.json.")

        print()
        generate_icons_map(union_icons, OUT_DIR)

    print("\nDone. Upload firmware/assets/icons/ to the Pico.")


if __name__ == "__main__":
    main()
