# assets/icons/ — Bootstrap icon font modules and lookup map for the Pico.
#
# Files that belong here (generated by tools/gen_icons.py, NOT committed unless
# you want them on the device):
#
#   icons_map.py              — compact Python dict: name -> unicode char
#   bootstrap_icons_24.py     — font_to_py-generated module for size 24
#   bootstrap_icons_36.py     — font_to_py-generated module for size 36
#   ...
#
# The source TTF and full JSON map live in:
#   assets/icons/bootstrap-icons.ttf
#   assets/icons/bootstrap-icons-map.json
#
# To regenerate, run from the project root:
#   python tools/gen_icons.py --icons alarm wifi arrow-up --sizes 24 36
