# Auto-generated by tools/lib/gen_icons.py — do not edit by hand.
# Re-run: ./tools/build-icons.sh

ICONS = {
    "cloud": "\uf2c1",  # cloud
    "cloud-drizzle": "\uf29d",  # cloud-drizzle
    "cloud-fog2": "\uf2a2",  # cloud-fog2
    "cloud-lightning-rain": "\uf2ab",  # cloud-lightning-rain
    "cloud-moon": "\uf2b0",  # cloud-moon
    "cloud-rain": "\uf2b6",  # cloud-rain
    "cloud-sun": "\uf2be",  # cloud-sun
    "clouds": "\uf2c3",  # clouds
    "moon": "\uf497",  # moon
    "quote": "\uf6b0",  # quote
    "snow": "\uf56d",  # snow
    "sun": "\uf5a2",  # sun
    "sunrise": "\uf5a5",  # sunrise
    "sunset": "\uf5a7",  # sunset
}


def get(name: str, fallback: str = "?") -> str:
    """Return the unicode glyph char for icon name, or fallback."""
    return ICONS.get(name, fallback)
